from datetime import datetime, timedelta, timezone
from database.db import execute_query, get_table


# ---------- Config ----------

FREQUENCY_CONFIG = {
    "DAILY": {"count": 14, "delta": timedelta(days=1)},
    "WEEKLY": {"count": 4, "delta": timedelta(weeks=1)},
    "BIWEEKLY": {"count": 4, "delta": timedelta(weeks=0.5)},
    "KITCHEN": {"count": 4, "delta": timedelta(weeks=1)},
}

ET_OFFSET = timezone(timedelta(hours=-5))


# ---------- Assignment Creation ----------

def add_job_assignments_to_db(assignments, start_date):
    """
    Create assignment ↔ job mappings and active assignments.
    assignment_id is generated by Postgres.
    """
    if isinstance(start_date, str):
        start_date = datetime.strptime(start_date, "%Y-%m-%d")

    weekdays = {
        "monday": 0, "tuesday": 1, "wednesday": 2,
        "thursday": 3, "friday": 4, "saturday": 5, "sunday": 6,
    }

    for row in assignments:
        job_name = row["Job Name"]
        username = row["Name"]

        print(f"Processing: {username} → {job_name}")

        # --- Job lookup ---
        job_rows = execute_query(
            "jobs",
            "select",
            filters=[("job_name", "eq", job_name)],
        )
        if not job_rows:
            print(f"Job '{job_name}' not found, skipping.")
            continue

        job = job_rows[0]
        job_id = job["job_id"]
        job_type = job["job_type"].upper()
        due_time_str = job.get("due_by_time", "12:00:00")

        if job_type not in FREQUENCY_CONFIG:
            print(f"Invalid job type '{job_type}', skipping.")
            continue

        # --- User lookup ---
        user_rows = execute_query(
            "users",
            "select",
            filters=[("username", "eq", username)],
        )
        if not user_rows:
            print(f"User '{username}' not found, skipping.")
            continue

        user_id = user_rows[0]["user_id"]
        hour, minute, second = map(int, due_time_str.split(":"))

        # --- First due date ---
        if job_type == "KITCHEN":
            due_at = start_date
            for day_name, weekday_num in weekdays.items():
                if day_name in job_name.lower():
                    days_ahead = (weekday_num - due_at.weekday() + 7) % 7
                    due_at += timedelta(days=days_ahead)
                    break
        elif job_type == "DAILY":
            due_at = start_date 
        elif job_type == "BIWEEKLY":
            due_at = start_date + timedelta(weeks=0.5)
        else:
            due_at = start_date + timedelta(weeks=1)

        due_at = due_at.replace(
            hour=hour,
            minute=minute,
            second=second,
            microsecond=0,
            tzinfo=ET_OFFSET,
        )

        # --- Create recurring assignments ---
        config = FREQUENCY_CONFIG[job_type]
        current_due = due_at

        for _ in range(config["count"]):
            # 1️⃣ Create assignment ↔ job mapping (Postgres generates assignment_id)
            #print("BEFORE EXECUTION")
            assignment_row = execute_query(
                "assignment_jobs",
                "insert",
                data={"job_id": job_id},
            )[0]
            #print("MADE IT HERE")
            assignment_id = assignment_row["assignment_id"]

            # 2️⃣ Create active assignment
            execute_query(
                "active_assignments",
                "insert",
                data={
                    "assignment_id": assignment_id,
                    "user_id": user_id,
                    "due_at": current_due.isoformat(),
                    "status": "ASSIGNED",
                },
            )

            current_due += config["delta"]

        print(f"Inserted {config['count']} assignments for {username} → {job_name}")


def add_makeup_jobs_to_makeup_table(jobs, start_date):
    """
    Create assignment ↔ job mappings and active assignments.
    assignment_id is generated by Postgres.
    """
    if isinstance(start_date, str):
        start_date = datetime.strptime(start_date, "%Y-%m-%d")

    weekdays = {
        "monday": 0, "tuesday": 1, "wednesday": 2,
        "thursday": 3, "friday": 4, "saturday": 5, "sunday": 6,
    }

    for row in jobs:
        job_name = row["Job Name"]

        print(f"Processing: {job_name}")

        # --- Job lookup ---
        job_rows = execute_query(
            "jobs",
            "select",
            filters=[("job_name", "eq", job_name)],
        )
        if not job_rows:
            print(f"Job '{job_name}' not found, skipping.")
            continue

        job = job_rows[0]
        job_id = job["job_id"]
        job_type = job["job_type"].upper()
        due_time_str = job.get("due_by_time", "12:00:00")

        if job_type not in FREQUENCY_CONFIG:
            print(f"Invalid job type '{job_type}', skipping.")
            continue

        hour, minute, second = map(int, due_time_str.split(":"))

        # --- First due date ---
        if job_type == "KITCHEN":
            due_at = start_date
            for day_name, weekday_num in weekdays.items():
                if day_name in job_name.lower():
                    days_ahead = (weekday_num - due_at.weekday() + 7) % 7
                    due_at += timedelta(days=days_ahead)
                    break
        else:
            due_at = start_date + timedelta(weeks=1)

        due_at = due_at.replace(
            hour=hour,
            minute=minute,
            second=second,
            microsecond=0,
            tzinfo=ET_OFFSET,
        )

        # --- Create recurring assignments ---
        config = FREQUENCY_CONFIG[job_type]
        current_due = due_at

        for _ in range(config["count"]):
            # 1️⃣ Create assignment ↔ job mapping (Postgres generates assignment_id)
            #print("BEFORE EXECUTION")
            assignment_row = execute_query(
                "assignment_jobs",
                "insert",
                data={"job_id": job_id},
            )[0]
            #print("MADE IT HERE")
            assignment_id = assignment_row["assignment_id"]

            # 2️⃣ Create active assignment
            execute_query(
                "makeup_jobs",
                "insert",
                data={
                    "original_assignment_id": assignment_id,
                    "due_at": current_due.isoformat(),
                },
            )

            current_due += config["delta"]

        print(f"Inserted {config['count']} assignments for  {job_name}")



# ---------- Permanent Makeup Job ----------

def make_makeup_job_assignments_to_db():
    """
    Create permanent Makeup Job (job_id = 0) and assign once per user.
    """
    # --- Ensure Makeup Job exists ---
    existing = execute_query(
        "jobs",
        "select",
        filters=[("job_id", "eq", 0)],
    )

    if not existing:
        execute_query(
            "jobs",
            "insert",
            data={
                "job_id": 0,
                "job_name": "Makeup Job",
                "job_description": "Permanent makeup job for all users",
                "num_hours": 1,
                "job_type": "MAKEUP",
                "due_by_time": "23:59:59",
            },
        )
        print("Created permanent Makeup Job.")

    users = get_table("users").select("*").execute().data
    far_future_due = datetime(
        2026, 12, 31, 23, 59, 0, tzinfo=ET_OFFSET
    ).isoformat()

    for user in users:
        user_id = user["user_id"]

        # Check if user already has a makeup assignment
        active = execute_query(
            "active_assignments",
            "select",
            filters=[("user_id", "eq", user_id)],
        )

        has_makeup = False
        for a in active:
            mapping = execute_query(
                "assignment_jobs",
                "select",
                filters=[("assignment_id", "eq", a["assignment_id"])],
            )
            if mapping and mapping[0]["job_id"] == 0:
                has_makeup = True
                break

        if has_makeup:
            continue

        # Create mapping (assignment_id generated by Postgres)
        assignment_row = execute_query(
            "assignment_jobs",
            "insert",
            data={"job_id": 0},
        )[0]

        # Create active assignment
        execute_query(
            "active_assignments",
            "insert",
            data={
                "assignment_id": assignment_row["assignment_id"],
                "user_id": user_id,
                "due_at": far_future_due,
                "status": "ASSIGNED",
            },
        )

    print("Permanent Makeup Job assigned where missing.")
